### ISSUE TITLE
delete big names file

### ISSUE THREAD

**Issue by mraasvel** [codam-coding-college/book-club#7]

**Comment by pde-bakk** [comment]
want me to revert/reset the commit or just delete it and still keep it in version control? @mraasvel

**Comment by mraasvel** [comment]
just delete it and keep it in version control so we can go back and laugh at it

**Comment by mraasvel** [comment]
or just keep it if you want to use it to show off tomorrow, I don't really care I just made this issue as a joke

**Comment by pde-bakk** [comment]
in that case, we keep it. Abi was gonna rewrite his binary search a little bit so he can parse files too
